name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - agent-master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2.4.0
      - name: Show workflow information
        id: get_filename
        run: |
          export _NAME=$(jq ".[\"$GOOS-$GOARCH\"].friendlyName" -r < .github/build/friendly-filenames.json)
          echo "_NAME: $_NAME"
          [ -z "$_NAME" ] && echo "Error: _NAME is empty" && exit 1
          echo "GOOS: $GOOS, GOARCH: $GOARCH, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV
      - name: Debug output
        run: |
          echo "ASSET_NAME from environment: $ASSET_NAME"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'
      - name: Get project dependencies
        run: go mod download

      - name: Build Server
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/server-vmess-agent -trimpath -ldflags "-s -w" ./cmd/server-agent
      - name: Build Mips softfloat Server
        if: matrix.goarch == 'mips' || matrix.goarch == 'mipsle'
        run: |
            GOMIPS=softfloat go build -v -o build_assets/server-vmess-agent-softfloat -trimpath -ldflags "-s -w" ./cmd/server-agent
      - name: Rename Windows Server
        if: matrix.goos == 'windows'
        run: |
          cd ./build_assets || exit 1
          mv server-vmess-agent server-vmess-agent.exe
      - name: Prepare to release
        run: |
          cp ${GITHUB_WORKSPACE}/README.md ./build_assets/README.md
          cp ${GITHUB_WORKSPACE}/LICENSE ./build_assets/LICENSE
      - name: Create ZIP archive
        shell: bash
        run: |
          pushd build_assets || exit 1
          touch -mt $(date +%Y01010000) *
          zip -9vr ../server-vmess-agent-$ASSET_NAME.zip .
          popd || exit 1
          FILE=./server-vmess-agent-$ASSET_NAME.zip
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >>$DGST
          done
      - name: Change the name
        run: |
          mv build_assets server-vmess-agent-$ASSET_NAME
      # Upload to artifacts

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: server-vmess-agent-${{ env.ASSET_NAME }}
          path: |
            ./server-vmess-agent-${{ env.ASSET_NAME }}
      # Upload binaries to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./server-vmess-agent-${{ env.ASSET_NAME }}.zip*
          tag: ${{ github.ref }}
          file_glob: true
